channels:
  - conda-forge
  - pyviz
dependencies:
  - numpy
  - scipy
  - hvplot
  - conda-forge::pyinterp
  - conda-forge::cmocean
  - holoviews
  - geoviews
  - cartopy
  - tabulate
  - datashader
  - netcdf4
  - pip
  - papermill
  - jupyter
  - pip:
    - mycolorpy
